services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
        networks:
            - discord-bot

    discord-bot:
        build: .
        restart: always
        env_file:
            - .env
        volumes:
            - ./src:/app/src
        depends_on:
            - db
        networks:
            - discord-bot

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_PORT: ${DB_PORT}
            PMA_USER: ${DB_USER}
            PMA_PASSWORD: ${DB_PASS}
        ports:
            - 8080:80
        links:
            - db
        depends_on:
            - db
        networks:
            - discord-bot

networks:
    discord-bot:
